"""
Django settings for app_config project.

Generated by 'django-admin startproject' using Django 1.11.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)

# --- Writable Data Sandbox for Clinical Environments ---
# Prevents "Run as Administrator" issues by moving DB/Logs to a user-writable path
if getattr(sys, 'frozen', False):
    if sys_platform := sys.platform == 'win32':
        KODYS_DATA_DIR = os.path.join(os.environ.get('LOCALAPPDATA', os.path.join(os.path.expanduser("~"), "AppData", "Local")), "KodysCAN")
    else:
        KODYS_DATA_DIR = os.path.join(os.path.expanduser("~"), ".kodys_can")
else:
    KODYS_DATA_DIR = BASE_DIR

if not os.path.exists(KODYS_DATA_DIR):
    os.makedirs(KODYS_DATA_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "^&6l41vym+d+o4s560lazu8#8-d_m(27mski$0x+wsvkd+&4+q"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "kodys",
]

# Use BigAutoField by default for primary keys (Django 3.2+ warning)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app_config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "kodys/templates"),
            os.path.join(BASE_DIR, "kodys/templates/pages"),
            os.path.join(BASE_DIR, "kodys/templatetags"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "app_config.context_processors.app_config",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(KODYS_DATA_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = "/static/"
DATA_URL = "/site_data/"
MEDIA_ROOT = os.path.join(KODYS_DATA_DIR, "media")
MEDIA_DATA = os.path.join(KODYS_DATA_DIR, "DATA")
DATA_UPLOAD_MAX_MEMORY_SIZE = 25000000

#########################################################################
# Kodys default user
#########################################################################
SERVICE_EMAIL = "balu.chenna@seaant.com"
DEFAULT_USER_EMAIL = "baluc0796@gmail.com"
DEFAULT_USER_PASSWORD = "secret123"
DEFAULT_USER_FIRSTNAME = "Kodys Administrator"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "baluc0796@gmail.com"
EMAIL_HOST_PASSWORD = "9942335457"
# LOGGING
##################################################################################################
LOGGER_FILE_NAME = "app"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "custom": {"format": "%(levelname)s %(asctime)s %(module)s %(message)s"},
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "null": {
            "class": "logging.NullHandler",
        },
        "appfile": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "formatter": "custom",
            "filename": os.path.join(KODYS_DATA_DIR, "app.log"),
            "when": "W4",
            "interval": 1,
            "backupCount": 7,
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
        },
    },
    "loggers": {
        "django.security.DisallowedHost": {
            "handlers": ["null"],
            "propagate": False,
        },
        "django.request": {
            "handlers": ["mail_admins"],
            "level": "ERROR",
            "propagate": True,
        },
        "app": {
            "handlers": ["appfile"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

LOGGING_CONFIG = "logging.config.dictConfig"


RUNNING_IN_APP = False

ECG_TESTING_DURATION = "00:01:00"

ECG_HRV_TESTING_DURATION = "00:05:00"

if RUNNING_IN_APP:
    MEDIA_URL = "http://127.0.0.1:5423/site_media/"
else:
    MEDIA_URL = "/site_media/"
SA_ACCOUNTAPP_EMAIL_REGEX = (
    r"[a-zA-Z0-9_.\-\+]+@[a-zA-Z0-9\-\_]+\.[a-zA-Z0-9]+(\.[a-zA-Z0-9]{2,4}){0,2}$"
)


if getattr(sys, 'frozen', False):
    # If frozen, we are in the root of the app bundle
    app_dir_path = os.path.dirname(sys.executable)
else:
    # If not frozen, we go up from app_config/settings.py
    app_dir_path = os.path.dirname(os.path.dirname(BASE_DIR))

# Robust search for wkhtmltopdf
REPORT_TO_PDF_PATH = os.path.join(app_dir_path, "wkhtmltopdf", "bin", "wkhtmltopdf.exe")

# Fallback to system path if bundled one is missing
if not os.path.exists(REPORT_TO_PDF_PATH):
    REPORT_TO_PDF_PATH = "wkhtmltopdf" 
