# Generated by Django 5.0.6 on 2026-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TX_MASTER_GENERATED_LICENSES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENT_NAME', models.CharField(max_length=255)),
                ('HOSPITAL_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('HARDWARE_ID', models.CharField(max_length=100)),
                ('GENERATED_KEY', models.CharField(max_length=100)),
                ('STATUS', models.CharField(default='ACTIVE', max_length=50)),
                ('NOTES', models.TextField(blank=True, null=True)),
                ('CREATED_ON', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_ON', models.DateTimeField(auto_now=True)),
                ('DATAMODE', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='A', max_length=1)),
            ],
            options={
                'db_table': 'TX_MASTER_GENERATED_LICENSES',
                'ordering': ['-pk'],
            },
        ),
    ]
