# Generated by Django 5.0.6 on 2026-03-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodys', '0002_tx_master_generated_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tx_master_generated_licenses',
            name='LAST_HEARTBEAT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tx_master_generated_licenses',
            name='VERSION_INFO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tx_master_generated_licenses',
            name='STATUS',
            field=models.CharField(default='PENDING_ACTIVATION', max_length=50),
        ),
    ]
