# Generated by Django 6.0.3 on 2026-03-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodys', '0003_tx_master_generated_licenses_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tx_master_generated_licenses',
            name='IS_ACTIVE',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tx_master_generated_licenses',
            name='MACHINE_NAME',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
